### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by GKarthikn92** [ManfredStoiber/stag-python#1]
i have installed all the pre-requisites as instructed and whenever i try to use 'pip install .' it shows an error as mentioned below: 
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1

your help is very much appreciated. thanks

**Comment by ManfredStoiber** [comment]
Hi, what is the output when you run `pip install -v .` in the project directory?

Best regards

**Comment by GKarthikn92** [comment]
hi, thanks for your swift response. Below is the error i am getting when i run as instructed. I am new to this and so please be kind enough to mention any silly mistake i might have made. 

(base) C:\Users\kg235\Downloads\stag-python-main\stag-python-main\stag-python>pip install -v .
Using pip 22.3.1 from C:\Users\kg235\anaconda3\lib\site-packages\pip (python 3.10)
Processing c:\users\kg235\downloads\stag-python-main\stag-python-main\stag-python
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=61
    Using cached setuptools-69.0.2-py3-none-any.whl (819 kB)
  Collecting setuptools-scm>=8.0
    Using cached setuptools_scm-8.0.4-py3-none-any.whl (42 kB)
  Collecting typing-extensions
    Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
  Collecting packaging>=20
    Using cached packaging-23.2-py3-none-any.whl (53 kB)
  Collecting tomli>=1
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Installing collected packages: typing-extensions, tomli, setuptools, packaging, setuptools-scm
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  conda-repo-cli 1.0.41 requires requests_mock, which is not installed.
  conda-repo-cli 1.0.41 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
  conda-repo-cli 1.0.41 requires nbformat==5.4.0, but you have nbformat 5.7.0 which is incompatible.
  Successfully installed packaging-23.2 setuptools-69.0.2 setuptools-scm-8.0.4 tomli-2.0.1 typing-extensions-4.9.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "C:\Users\kg235\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
      main()
    File "C:\Users\kg235\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\kg235\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\kg235\AppData\Local\Temp\pip-build-env-9ipa1nse\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\kg235\AppData\Local\Temp\pip-build-env-9ipa1nse\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\kg235\AppData\Local\Temp\pip-build-env-9ipa1nse\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 13, in <module>
    File "C:\Users\kg235\anaconda3\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1645: character maps to <undefined>
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\kg235\anaconda3\python.exe' 'C:\Users\kg235\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\kg235\AppData\Local\Temp\tmpfmmtczb_'
  cwd: C:\Users\kg235\Downloads\stag-python-main\stag-python-main\stag-python
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

**Comment by ManfredStoiber** [comment]
Ah you're using Windows, this is an issue I also came across yesterday. I made a pretty big update to the code a few hours ago, if you use the latest version your problem should be fixed.

It is also currently building and packaging right now. In a few hours it should be finished and uploaded to PyPI, which means you then can install the whole package without having to deal with the prerequisites by simply using `pip install stag-python`.

I'll let you know when it's ready.

**Comment by ManfredStoiber** [comment]
It should work now using only `pip install stag-python`. Please give it a try and let me know if it works.

**Comment by GKarthikn92** [comment]
Thank you so much for your efforts and response. will try and let you know!

**Comment by GKarthikn92** [comment]
working great! thank you once again!

**Comment by ManfredStoiber** [comment]
You're welcome!
