### ISSUE TITLE
corners coordinates convention

### ISSUE THREAD

**Issue by tflueckiger** [ManfredStoiber/stag-python#3]
Hi, 

I just ran a detection test over the sample marker id=0 of the family HD19 (https://drive.google.com/drive/folders/0ByNTNYCAhWbIM21SOWRKV1FGTTA?resourcekey=0-9aiS0u--y5WQ2nrkctOGKQ). 

The image has size 1000x1000.
The returned corners are : 
[[100. 100.]
 [899. 100.]
 [899. 899.]
 [100. 899.]]

From the detected corners, it looks like the marker has a size of 799x799. Is this intentional ? I do not understand why the corners are not centered in the image. I was expecting 
[[100. 100.]
 [900. 100.]
 [900. 900.]
 [100. 900.]]

Thank you very much for your help. 
 
Best.

Tim

**Comment by tflueckiger** [comment]
Also, I took an image of a printed marker and it is normal that the returned corners coordinates are always integer ? 
Is there any way to activate a refinement of the coordinates to obtain subpixel coordinates ?

Thank you

**Comment by ManfredStoiber** [comment]
Hi Tim,

sorry for the late reply, I was busy finishing my Master's Thesis and haven't had the chance to look into your issue until now.

Your detection test works like intended, as the coordinates function as pixel indices, starting from 100 and going up to 899, which counts 800 pixels in sum.

To illustrate what I want to say, consider the following example with a marker 10x10 pixels in size:
![image](https://github.com/user-attachments/assets/daa6b573-3851-4deb-b851-c21ffc87fce7)

In this case, the detected coordinates would be:
[[0, 0],
[9, 0],
[9, 9]
[0, 9]]

I hope this example clarifies things. If not, please don't hesitate to ask!

Currently, there is no specific feature to activate a refinement to obtain subpixel coordinates. But the values are just clipped to integers, and honestly, I can't recall why I clipped the values in the first place. So if you are still interested, I could disable this clipping.

Best regards

**Comment by ManfredStoiber** [comment]
Hi again,

the latest version (v1.1.0) now comes with the full sub-pixel resolution and can be installed via pip.
If you face any problems or have additional questions, please don't hesitate to reopen this issue or create a new one.

Kind regards
