### ISSUE TITLE
is there a function that provides the pose of the marker?

### ISSUE THREAD

**Issue by suchowitzkyAMI** [ManfredStoiber/stag-python#5]

**Comment by ManfredStoiber** [comment]
Hi,

in this project, there is no dedicated function for pose estimation, as this is typically accomplished using the [cv::solvePnP()](https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d) function of OpenCV. Please have a look at this [Tutorial](https://docs.opencv.org/4.x/d5/dae/tutorial_aruco_detection.html) for an example. The corresponding Python functions are documented in the OpenCV documentation.

The STag library is designed to serve as a drop-in replacement for the ArUco library, so you can easily replace it with this library in your projects.

Best regards
