### ISSUE TITLE
C++ / Python inconsistency : int point coordinates instead of the original float

### ISSUE THREAD

**Issue by Q4pLJ1yy** [ManfredStoiber/stag-python#6]
Hi,
It seems DetectMarkers has not the same behavior between the original C++ and this Python wrapper : convertToTuple applies a cast to int that is not present in the C++ library :
`std::vector<std::vector<float>> contours_vec;
 for (cv::Point2f pt : corners[i]) {
            contours_vec.push_back({static_cast<float>((int)pt.x), static_cast<float>((int)pt.y)});
  }`
Is this type cast to int necessary between float and Point2f ? The accuracy pointed out in the original paper must be downgraded by this step.

**Comment by ManfredStoiber** [comment]
Hi,
as mentioned in [this issue](https://github.com/ManfredStoiber/stag-python/issues/3), I honestly can't recall the exact reason why I originally clipped the values to integers. I tested it without clipping and had no problems. If you'd like, I can build and distribute a new version without the casting.

Best regards

**Comment by Q4pLJ1yy** [comment]
Hi,
That would be great, I had some issues compiling locally. I am interested too by the full resolution of the output for a Python testbed, if only to see if I can improve positioning results compared to regular subPixelCorners applied after the fact. Thanks !
Best regards

**Comment by ManfredStoiber** [comment]
The new version with the full sub-pixel resolution (v1.1.0) is now available in PyPI and can be installed via pip.
If you face any problems or have additional questions, please don't hesitate to reopen this issue or create a new one.

Best regards!
